/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TangibleNFT } from "./TangibleNFT";

export { TangibleNFT__factory } from "./factories/TangibleNFT__factory";
