/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GoldBarBond } from "./GoldBarBond";
export type { GoldBarCalc } from "./GoldBarCalc";

export { GoldBarBond__factory } from "./factories/GoldBarBond__factory";
